# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('RDY', 'Publicado'), ('INP', 'No publicado')], default='INP', max_length=3),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'Pública'), ('PRI', 'Privada')], default='PUB', max_length=3),
        ),
    ]
